# Generated by Django 2.0.6 on 2018-07-03 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='soazibaseuser',
            table='user',
        ),
    ]
