# Generated by Django 2.0.6 on 2018-07-03 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=128, verbose_name='标题')),
                ('description', models.CharField(max_length=256, verbose_name='描述')),
                ('content', models.TextField(verbose_name='内容')),
                ('visits', models.PositiveIntegerField(default=0, verbose_name='浏览数量')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='点赞数量')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '文章列表',
                'verbose_name_plural': '文章列表',
                'db_table': 'bbs_article',
            },
        ),
        migrations.CreateModel(
            name='CodeList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, verbose_name='语言')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '语言分类',
                'verbose_name_plural': '语言分类',
                'db_table': 'bbs_code',
            },
        ),
        migrations.CreateModel(
            name='LabelList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=24, verbose_name='标签')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbs.ArticleList', verbose_name='标题')),
            ],
            options={
                'verbose_name': '标签列表',
                'verbose_name_plural': '标签列表',
                'db_table': 'bbs_label',
            },
        ),
        migrations.CreateModel(
            name='ReplyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=512, verbose_name='内容')),
                ('likes', models.PositiveIntegerField(verbose_name='点赞数量')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='回复时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbs.ArticleList', verbose_name='标题')),
            ],
            options={
                'verbose_name': '回复列表',
                'verbose_name_plural': '回复列表',
                'db_table': 'bbs_reply',
            },
        ),
        migrations.AddField(
            model_name='articlelist',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbs.CodeList', verbose_name='分类'),
        ),
    ]
